### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/terraformer#14]
Gardener informs its stakeholders in its [CNCF CII Badge](https://bestpractices.coreinfrastructure.org/en/projects/1822#analysis), that static code checks are applied by using Checkmarx. This repository has findings, which have to be assessed by the component owner(s). As required all prio high findings were already been immediately assessed. Please find the timeline until when to assess the remaining prio medium findings  in the [Wiki](https://wiki.wdf.sap.corp/wiki/display/Kubernetes/Static+Code+Analysis#StaticCodeAnalysis-Timeline) (restricted access).  At the time being you can ignore the prio low findings. Please find background information and a link to the Checkmarx project for your repository in the [Wiki](https://wiki.wdf.sap.corp/wiki/display/Kubernetes/Static+Code+Analysis#StaticCodeAnalysis-CheckMarxProjects) (restricted access). In the [Wiki](https://wiki.wdf.sap.corp/wiki/display/Kubernetes/Static+Code+Analysis#StaticCodeAnalysis-CheckmarxLogin) (restricted access) you will as well find information how to get a Checkmarx user which is required to be able to do your assessment in the Checkmarx Web UI.

**Comment by hoeltcl** [comment]
This issue must be resolved until **January 18th 2019** latest. Please contact [ThormaehlenFred ](https://github.com/ThormaehlenFred) or [hoeltcl ](https://github.wdf.sap.corp/hoeltcl)if not already done.

**Comment by rfranzke** [comment]
I have already discussed some weeks ago with @ThormaehlenFred that the Protecode job for the `terraformer` repository is misconfigured. It **does not** check the `terraformer` but the `dashboard` repository.
Hence, I close the issue now. Please reopen once the job is configured correctly and reports findings.

**Comment by ThormaehlenFred** [comment]
This is a misunderstanding: This issue is about Checkmarx (not Protecode) and here the job is configured correctly to scan https://github.com/gardener/terraformer

**Comment by rfranzke** [comment]
I meant Checkmarx, sorry. No, it is not. Check the latest scan from 12/15/2018 - it scanned the `dashboard` repo.

**Comment by ThormaehlenFred** [comment]
This is a bug in Checkmarx. I opened a Checkmarx [ticket 1324](https://sectest.mo.sap.corp/rt/SelfService/Display.html?id=1324). I will reopen this issue when the ticket is processed.
