### ISSUE TITLE
[Alicloud] API Service Cert issue

### ISSUE THREAD

**Issue by jia-jerry** [gardener/terraformer#17]
We are going to use k8s provided by Alicloud as Garden and Soild cluster. Currently we met an issue when access API Server inside the terraformar container, even we specified a CA file which exists in kube-config. The **curl** failed with TLS handshake error.

Root cause:
Alicloud uses their own Root CA to generate an intermediate CA file. Then it use this intermediate CA to sign TLS certs and keys. 

**curl**  fails only intermediate CA is specified in --cacert.

**Comment by minchaow** [comment]
According to this issue, two solution proposed by my side:
1. Modify "terraform.sh" file and add `--insecure` flag behind `curl` command.
2. Customize container image in which running script "terraform.sh", and add Alicloud Root CA and intermediate CA into `$PATH_CACERT`.

I prefer to the first solution. If we choose the second solution, there are a few other efforts to maintain the customized image. 

@rfranzke,could you please help give some comments about this issue. Thank a lot.

**Comment by jia-jerry** [comment]
Another option is to use **kubectl**.
