### ISSUE TITLE
Scaling down parallelism to 0 

### ISSUE THREAD

**Issue by afritzler** [gardener/terraformer#22]
Before I create any PRs here: what would be the runtime penalty if we would decrease the parallelism to 0? The reason I am asking is, that on some infrastructures (like some OpenStack installations) there might be an issue when we are creating things "too fast" in the infrastructure. As an example: this is in particular problematic in the context of creating router instances which are backed by certain hardware appliances.

**Comment by rfranzke** [comment]
I'm not sure whether I understood your point. In the example manifest in this repo and in the [actual manifest in gardener/gardener](https://github.com/gardener/gardener/blob/master/pkg/operation/terraformer/terraformer.go#L303-L330) we set `.spec.parallelism=1` (or we don't even set it which means that the field will be defaulted to `1`).
Consequently, we don't create more than one Terraformer pod at a time. Can you explain how the "too fast creation" of things is related to the `.spec.parallelism`?

**Comment by afritzler** [comment]
I mean the terraform parallelism itself. When I see this correctly, we are currently using 4 as a default https://github.com/gardener/terraformer/blob/master/terraform.sh#L147

**Comment by afritzler** [comment]
I am referring to this property here https://www.terraform.io/docs/commands/apply.html#parallelism-n

**Comment by rfranzke** [comment]
Ah okay, thank you. Other than longer runtimes I cannot think about any penalties.

**Comment by afritzler** [comment]
The best way of course would be to make this a config in the infrastructure extension.

**Comment by rfranzke** [comment]
The infrastructure extensions deploy the Terraformer on their own, so they could control how this field is set 👍

**Comment by ialidzhikov** [comment]
@afritzler , @rfranzke , is this issue still actual? If not, can we close it?

**Comment by rfranzke** [comment]
I don't think it's relevant anymore, let's close it for now and reopen in case we need it again.
/close
