### ISSUE TITLE
[terraformer] run container as non-admin

### ISSUE THREAD

**Issue by bzumhagen** [gardener/terraformer#61]
**How to categorize this issue?**
/area security
/kind enhancement
/priority normal

**What would you like to be added**:
I would like the container to be run as a non-root user.

**Why is this needed**:
Security policies in my cluster prevent containers from being executed which run under root permissions.

See https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups for the specific policy in question.

**Comment by timebertt** [comment]
/unassign
I'm currently blocked with several higher priority tasks and there hasn't been much progress on this, yet.

**Comment by timebertt** [comment]
/close as there is no progress on this issue.
Kindly `/reopen` if you see the necessity.
