### ISSUE TITLE
Enable dynamic loading of terraform plugins

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/terraformer#74]
**How to categorize this issue?**

/area operations
/kind enhancement
/priority normal

**What would you like to be added**:
Add the option to have terraform load necessary provider plugins during runtime. In addition, also generate one image without any pre-installed terraform plugins.

**Why is this needed**:
Currently, there are multiple images being built for the terraformer, containing different sets of pre-installed provider plugins which are then given to the `terraform init` command here: https://github.com/gardener/terraformer/blob/master/pkg/terraformer/terraformer.go#L186
While this is very nice for the Gardener, where there is a fixed scope that allows defining a fixed set of needed terraform plugins, we would like to use the terraformer also for the [landscaper](https://github.com/gardener/landscaper) terraform deployer. This terraform deployer is meant to be able to execute arbitrary terraform operations, which means that it cannot be limited to a pre-defined set of necessary plugins. 
As the `-plugin-dir` argument mentioned above disables the dynamic installation of missing terraform plugins, we would like to have the option - e.g. in form of an command-line argument to the terraformer - to remove it, causing terraform to install the missing providers on demand. 
It would also be nice to have a terraformer image without any pre-installed plugins available, as we don't need them anyway for this scenario.

**Comment by timebertt** [comment]
I have several concerns about your proposal:

- dynamically loading binaries in the container during runtime contradicts to one of the main motivations for containerization: having a shippable, standalone bundle of software
- dynamically loading tf plugins does not work in restricted environments where there is no/restricted internet access
- also, this doesn't sound like a great idea to me from a security point of view: it opens a huge hole for vulnerabilities and there's no way of scanning components/plugins beforehand (cc @ThormaehlenFred @vlerenc)

Would it be acceptable in your usecase to leverage different pre-build image variants for deployments targeting different providers?

**Comment by Diaphteiros** [comment]
cc @schrodit

**Comment by Diaphteiros** [comment]
cc @ccwienk 

I just discussed the problems that @timebertt mentioned with @schrodit and we had another idea on how to solve this:
Instead of dynamically installing the required tf providers, we define them as a dependency in the component descriptor. This allows scanning as well as using it within restricted environments. Before running the terraformer, we then run an init container that mounts the specified tf plugins into the terraformer container.
We would still want to have an 'empty' terraformer image without any pre-installed plugins for this, but installing terraform plugins during runtime would not be necessary anymore.

WDYT?

**Comment by timebertt** [comment]
> Before running the terraformer, we then run an init container that mounts the specified tf plugins into the terraformer container.

That sounds like a good idea and more close to the cloud-native idea, I guess 😉
