### ISSUE TITLE
Not possible to delete Shoot with wrong floatingPoolName

### ISSUE THREAD

**Issue by timuthy** [gardener/terraformer#78]
**How to categorize this issue?**

/area ops-productivity
/area usability
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:
Shoots can be deleted with invalid floating pool name configuration.

**Why is this needed**:
Today, if a shoot is created with an invalid floating pool name configuration, the reconciliation will fail but the user is also not able to delete the shoot afterwards:

```
-> Pod '.tf-destroy' reported:
* Your query returned no results. Please change your search criteria and try again.
  on tf/main.tf line 15, in data "openstack_networking_network_v2" "fip":
  15: data "openstack_networking_network_v2" "fip" {
```

Operators need to manually delete the `infrastructure` object in order to proceed with the deletion. This shouldn't be required.

Thanks for the investigation @dkistner and @ialidzhikov.

**Comment by vpnachev** [comment]
> > Conceptually the finalizer check on deletion should take place only if the terraformer has run successfully at least once.
> 
> I think this won't be possible since Terraformer is also the one maintaining the finalizer

There is a possibility terraformer to create some of the resources but still the `apply` to fail. In this case it is fine that the finalizers are set and not skipped.

> we need a second "isEmpty" check in the Terraformer which skips the destroy action in case the state is void.

Sounds good to me.
